# Generated by Django 3.2.5 on 2023-03-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(default='contributor', max_length=15),
        ),
    ]
